services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mysql_db
      - redis_cache
    links:
      - redis_cache
      - mysql_db

  mysql_db:
    image: mysql:9.1
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis_cache:
    image: redis:7.4.1-alpine
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  test:
    profiles: ["test"]
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: gradle test
    env_file:
      - .env

volumes:
  mysql_data:
  redis_data: